FROM bitnami/spark:3.5.0

USER root
RUN apt update 
RUN apt list --upgradable
RUN apt update && apt install -y wait-for-it
#netcat
RUN apt install curl apt-utils iputils-ping -y
RUN apt update
RUN apt install netcat-openbsd -y
RUN apt update  
RUN apt install -y python3-pip 

USER 1001
RUN pip3 install --no-cache-dir wheel 
RUN pip3 uninstall -y pyspark || true 
RUN pip3 install --no-cache-dir pyspark==3.5.0 delta-spark==3.2.0 

USER root
RUN echo 'spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension' >> /opt/bitnami/spark/conf/spark-defaults.conf 
RUN echo 'spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog' >> /opt/bitnami/spark/conf/spark-defaults.conf 
RUN echo 'spark.hadoop.fs.defaultFS hdfs://namenode:8020' >> /opt/bitnami/spark/conf/spark-defaults.conf 
RUN echo 'spark.hadoop.hive.metastore.uris thrift://hive-metastore:9083' >> /opt/bitnami/spark/conf/spark-defaults.conf 
RUN echo 'spark.sql.catalogImplementation hive' >> /opt/bitnami/spark/conf/spark-defaults.conf 
RUN echo 'Configuration terminée, démarrage de Spark Shell...' && \
    /opt/bitnami/spark/bin/spark-shell \
    --master spark://spark-master:7077 \
    --packages io.delta:delta-spark_2.12:3.2.0 \
    --repositories https://repo1.maven.org/maven2/

#RUN mv conf/spark-env.sh.template conf/spark-env.sh
#RUN chmod 776 /opt/bitnami/spark/conf/spark-env.sh


